### ISSUE TITLE
Teletext overlay too large

### ISSUE THREAD

**Issue by smallint** [xbmc-imx6/xbmc#11]
I am not sure if this is related to xbmc in general or just our port. The teletext overlay is too large and I can only see the upper left quarter of it especially with HD playback.

**Comment by koying** [comment]
Probably XBMC related. I've seen similar complains re karaoke text in XBMC's forums...
Would you happen to have another platform to test?

**Comment by smallint** [comment]
I am going to try it on my notebook ...

**Comment by smallint** [comment]
It is working correctly on my notebook (Linux). Maybe it is a general GLES2 rendering issue?

**Comment by koying** [comment]
Yep, probably. I'm looking into it

**Comment by smallint** [comment]
Thank you. I tried once looking at it as well but got lost in the code and was too much focused on deinterlacing and stuff. ;)

**Comment by emveepee** [comment]
For me telextext works correctly at 1280x720 but not at 1920x1080

Martin

**Comment by koying** [comment]
Could you try with the following patch and report, please:

```
diff --git a/xbmc/guilib/GUITextureGLES.cpp b/xbmc/guilib/GUITextureGLES.cpp
index df47ced..cc1bddc 100644
--- a/xbmc/guilib/GUITextureGLES.cpp
+++ b/xbmc/guilib/GUITextureGLES.cpp
@@ -260,6 +260,13 @@ void CGUITextureGLES::DrawQuad(const CRect &rect, color_t color, CBaseTexture *t

   glUniform4f(uniColLoc, col[0] / 255.0f, col[1] / 255.0f, col[2] / 255.0f, col[3] / 255.0f);

+  ver[0][0] = ver[3][0] = rect.x1;
+  ver[0][1] = ver[1][1] = rect.y1;
+  ver[1][0] = ver[2][0] = rect.x2;
+  ver[2][1] = ver[3][1] = rect.y2;
+  ver[0][2] = ver[1][2] = ver[2][2] = ver[3][2]= 0;
+
+  /*
   // Setup vertex position values
   #define ROUND_TO_PIXEL(x) (float)(MathUtils::round_int(x))
   ver[0][0] = ROUND_TO_PIXEL(g_graphicsContext.ScaleFinalXCoord(rect.x1, rect.y1));
@@ -274,6 +281,7 @@ void CGUITextureGLES::DrawQuad(const CRect &rect, color_t color, CBaseTexture *t
   ver[3][0] = ROUND_TO_PIXEL(g_graphicsContext.ScaleFinalXCoord(rect.x1, rect.y2));
   ver[3][1] = ROUND_TO_PIXEL(g_graphicsContext.ScaleFinalYCoord(rect.x1, rect.y2));
   ver[3][2] = ROUND_TO_PIXEL(g_graphicsContext.ScaleFinalZCoord(rect.x1, rect.y2));
+  */
   if (texture)
   {
     // Setup texture coordinates
```

**Comment by smallint** [comment]
Yep, works fine for SD channels. Still need to test HD but should not make a difference..

**Comment by koying** [comment]
Well, according to @emveepee the resolution matters, so please test it, too.

**Comment by smallint** [comment]
Wasn't he talking about HD screen resolution? I meant HD stream resolution. Going to test it asap.

**Comment by smallint** [comment]
It is working for 1280x720 and 1920x1080 streams on a 1920x1080 screen as well. ;)

**Comment by koying** [comment]
Cool. Thanks.
I'll upstream that ;)

**Comment by emveepee** [comment]
I will try the patch this evening.  To be clearer I was writing about SD teletext being oversized at 1080p but fine at 720p.  I don't even have any HD samples with telext (V key) just DVB subtitles.  Here in Canada we only have ATSC subtitles and they aren't even supported in XBMC at the moment.

Built with the patch and yes it does fix that bug.

Martin

**Comment by koying** [comment]
Upstreamed and already merged.

**Comment by emveepee** [comment]
I guess when a change is upstreamed with a PR here, I guess that means it is lost to this for until the next time they are synced?  Or am I missing something?

Martin

**Comment by koying** [comment]
Well, yes. I haven't PR'ed here as it was a pure XBMC issue.
