### ISSUE TITLE
Nothing on display?

### ISSUE THREAD

**Issue by koying** [xbmc-imx6/xbmc#15]
Has anyone else the issue that XBMC is starting normally but nothing appears on output besides the console prompt?

What I can think of:
- XBMC is outputting to the wrong fb
- the wrong fb is shown on the hdmi output
- the fb is fully transparent

**Comment by smallint** [comment]
Black screen? ;)
Sorry, haven't seen that so far ...

**Comment by koying** [comment]
Good for you ;)
It's not a black screen, I see the console...

**Comment by wolfgar** [comment]
Yes I have seen this exact behavior one time...
I have killed xbmc and relaunched and it was ok 
I vote for XBMC is outputting to the wrong fb or initialization error...

**Comment by smallint** [comment]
Yesterday two times. I could quit xbmc by blindly navigating to the exit button. Restarting it helped.
