### ISSUE TITLE
Dropped frames/bumpy playback (LiveTV)

### ISSUE THREAD

**Issue by smallint** [xbmc-imx6/xbmc#18]
Before sending logs I just switched back to the TSManager  implementation and it works again. Even after heavy discontinuities the playback recovers immediately to "smooth" mode. The downside is that horizontal scrollers are not perfectly smooth anymore. Since the latter can be compensated by the motion plus feature of the screen I personally prefer the TSManager approach in terms of visual experience.

I also noticed that a frame should not be displayed if the flag VPU_DEC_OUTPUT_MOSAIC_DIS is set according to libfslvpuwrap and the gstreamer-implementation. I created a branch (fixignmosaic) to address this issue.

I am going to test Chris priority pts queue as well.

**Comment by smallint** [comment]
The playback issue is solved with Chris' pts queue. I am not sure if the mosaic fix is also necessary but I have it compiled in as well. It does not seem to hurt.

**Comment by wolfgar** [comment]
As I already said in previous issue regarding pts, we have to speak with data and share samples.
I have just sent to you a link to do so.

**Comment by smallint** [comment]
It is hard to share samples in my case. I am playing with LiveTV mostly for testing and I am not sure if the drop/discontinuity also in the stream on disc. tvheadend does not report anything in this regard. Might be related to the streaming itself. I just wanted to report back since the differences are huge compared to my setup. I am going to test more in live mode and try to prepare samples.

**Comment by wolfgar** [comment]
I understand it is not easy to catch Jan but maybe you can record with tvheadend and hopefully we will see the same behavior in the recorded stream...

**Comment by smallint** [comment]
I am closing this now since this particular bug is fixed with #28.
