### ISSUE TITLE
Video playback misalignment

### ISSUE THREAD

**Issue by emveepee** [xbmc-imx6/xbmc#24]
I have problems with 1080i video recording and live showing no video/green bar at the top and misaligned colours in the video itself it shows on keys an edges.  This is on the 3.10.30 kernel and in 3.0.35 too.

Windowed [IMG]http://i.imgur.com/YNmGHGH.jpg[/IMG] and full screen it shows the problem but it is within the overscan error so I don't see it with 0,0 calibration
[IMG]http://i.imgur.com/cOunocQ.png[/IMG]

Martin

**Comment by wolfgar** [comment]
The same for me as I alluded in #17
@chris : the file interlaced.ts in my shared folder exhibits this issue...

**Comment by koying** [comment]
Fixed in https://github.com/xbmc-imx6/xbmc/pull/25

**Comment by emveepee** [comment]
Works great now thanks.

Martin
