### ISSUE TITLE
Sample of a video that doesn't work well (xvid)

### ISSUE THREAD

**Issue by cjcr** [xbmc-imx6/xbmc#30]
Hi guys,

First thank you for all the great work you're doing with imx6 and xbmc ... is great!

I found a video that have problems with framerate and sync lips.

<b>Device:</b> Matrix TBS (IMX6Q) SABRESD.
<b>Kernel:</b> Linux matrixtv 3.0.35-2666-gbdde708 #1 SMP PREEMPT Tue Feb 18 22:06:41 CET 2014 armv7l GNU/Linux

<b>File Info (MediaInfo Windows):</b>
Format                         : AVI
Format/Info                    : Audio Video Interleave
File size                      : 35.8 MiB
Duration                       : 3mn 40s
Overall bit rate               : 1 362 Kbps
Writing library                : TMPGEnc 3.0 XPress Version. 3.0.4.24
Comment                        : .ooOO ROSA MANNEN 2007 OOoo.

Video
ID                             : 0
Format                         : MPEG-4 Visual
Format profile                 : Advanced Simple@L5
Format settings, BVOP          : Yes
Format settings, QPel          : No
Format settings, GMC           : No warppoints
Format settings, Matrix        : Default (H.263)
Codec ID                       : XVID
Codec ID/Hint                  : XviD
Duration                       : 3mn 40s
Bit rate                       : 1 193 Kbps
Width                          : 716 pixels
Height                         : 424 pixels
Display aspect ratio           : 1.689
Frame rate                     : 25.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.157
Stream size                    : 31.3 MiB (88%)
Writing library                : XviD 1.1.0 Beta2 (UTC 2005-04-04)

Audio
ID                             : 1
Format                         : MPEG Audio
Format version                 : Version 1
Format profile                 : Layer 3
Mode                           : Joint stereo
Mode extension                 : MS Stereo
Codec ID                       : 55
Codec ID/Hint                  : MP3
Duration                       : 3mn 40s
Bit rate mode                  : Constant
Bit rate                       : 160 Kbps
Channel(s)                     : 2 channels
Sampling rate                  : 48.0 KHz
Compression mode               : Lossy
Stream size                    : 4.20 MiB (12%)
Alignment                      : Split accross interleaves
Interleave, duration           : 125 ms (3.12 video frames)
Writing library                : LAME3.96

<b>Sample download (music video - 36mb):</b> https://www.dropbox.com/s/adrxfl6dpd9rs3z/Travis%20-%20The%20Beautiful%20Occupation.avi

**Comment by smallint** [comment]
I haven't tested it yet but what version of the code did you use? There is still PR #28 outstanding which should address this issue if you did build from master.

**Comment by koying** [comment]
I've tested AVI's yesterday and #28 doesn't solve the problem, yet.
@wolfgar has still to add the workaround of not using the pts at all for avi's...

**Comment by cjcr** [comment]
@smallint 2db31cf74e.

I saw this problem in others AVI I have (with xvid codec) ...

**Comment by wolfgar** [comment]
@koying : I am dubious #28 should drop the dts substitution which is responsible for issues for AVI containers...
I have just played this sample with master + merged fixpts branch it seems ok
I also tried 3 other avi files (including your sample) and they are ok... 
(with#28 of course, it is not ok with master we all agree of this one at least)

**Comment by koying** [comment]
Strange. I tried sample.avi yesterday and it was desynced.
I'll redo the tests.

**Comment by koying** [comment]
Even stranger: I tested yesterday and the avi was fine ;)

**Comment by wolfgar** [comment]
OK no problem... I close this ticket and we will open a new one if the issue occurs with the new master

**Comment by koying** [comment]
@Cjcr Just for confirmation, your sample works fine for me with #28

**Comment by cjcr** [comment]
@koying Yeah, now works really nice! 
Great work guys! :)
