### ISSUE TITLE
HDMI-CEC

### ISSUE THREAD

**Issue by koying** [xbmc-imx6/xbmc#37]
I've seen @wolfgar has also worked on integration of imx cec support in libcec.
Might be a good idea to bring the cec project under this umbrella, with the aim of producing a PR vs. libcec master?

**Comment by wolfgar** [comment]
Yes it is a nice idea.
For an introduction to my work, you can read this [post](http://stephan-rafin.net/blog/2013/09/30/i-mx6-cec/)
I  will add the repo next week

**Comment by wolfgar** [comment]
I have just forked the libcec for imx6 version here...
Note that we also depend upon a patch for the kernel driver itself for the whole thing to work

**Comment by wolfgar** [comment]
Yesterday I was in a hurry  : I have just fixed the initial import by properly forking libcec and by pushing the rebased support for iMX6.
The issues are enabled on the repository.
Starting from now, libcec for iMX6 will be dealt with here...

**Comment by koying** [comment]
Great.
I've seen that your patch has been included in cubox-i's kernels...

**Comment by wolfgar** [comment]
This is great : I noticed that geexbox image had working cec but was unsure whether it was added as a geexbox patch or already included in kernel...

I have also updated my blog post to point here
I close this ticket now : we can disccuss cec stuff in libcec repo...
