### ISSUE TITLE
Vsync lost after switching off/on display

### ISSUE THREAD

**Issue by smallint** [xbmc-imx6/xbmc#38]
When I switch off and on again the display with a running xbmc instance vsync is lost or at least correct screen synchronization which causes tearing. This seems to be a driver issue as xbmc itself cannot do much here I think. Do others have the same problem?

**Comment by koying** [comment]
I haven't seen this, but I'm not sure I've yet let xbmc run untouched from one viewing session to another w/o recompiling ;)

**Comment by smallint** [comment]
You can test is easily. Just switch off your display while xbmc is running and switch it on again. The time between does not matter. You would notice the issue immediately in the GUI already.

**Comment by koying** [comment]
I cannot seem to be able to reproduce...

**Comment by smallint** [comment]
Hmmm ... ok ... it is probably related to my display. I'll keep an eye on it and close this issue as Stephan isn't able to reproduce it, too.
