### ISSUE TITLE
Deinterlacing support

### ISSUE THREAD

**Issue by smallint** [xbmc-imx6/xbmc#4]
To support deinterlacinging I see two ways:
1. Use XBMC built in deinterlacing methods which might be slow due to memory copying
2. Utilize IMX6 IPU on decoded VPU buffers

I would go for 2. and try to implement it. Anyone already working on this?

**Comment by koying** [comment]
Yeah. Any memory copy of DMA mem inside xbmc should be avoided at all cost because it is dead slow.
When I tetsted, copying a 1080p frame to CPU memory took ~40ms ;)

**Comment by smallint** [comment]
I assign myself to this task. If someone wants to jump in, let me know.

**Comment by wolfgar** [comment]
The grace period to answer was quite short to expire ;)
Unfortunately, on my side, do no expect answer during the daylight : I am free to work on funny things only at night...
More seriously, that's fine, go for it. I Agree that IPU appears to me as the best option (even if it is against "platform agnostic" concept of xbmc, after all we are working on the imx specific part and we do not want to ignore this nice deinterlacing engine...)
I don't know if you are aware of it but you may have a useful code sample here : https://github.com/rogeriorps/ipu-examples/blob/master/mx6/deinterlacing/example1/dint_ex1.c

**Comment by smallint** [comment]
Yep, I read it already and am currently experimenting with it.

**Comment by smallint** [comment]
I pushed my current version into feature/deinterlacing. It is not working or better it is producing black frames for me. The internal interface is now such that there is an additional pool of IPU frames that is passed to the renderer instead of the decoded VPU frames. The VPU frames are attached as source and deleted accordingly. The system itself seems to work: no crashes and it is still working for non interlaced streams. Documentation is quite hard to find on that topic. If you want to have a look, the most important thing is going on in DVDVideoCodecIMX.cpp:1040. My idea as follows (maybe it is conceptual wrong):
- VPU decodes frames (DMA)
- Pass them (DMA) to IPU (DMA) to be deinterlaced (NV12->NV12)
- Pass the mapped DMA memory to the renderer update the texure with glTexDirectVIVMap

Everything is managed with reference counting and dependencies are automatically tracked, so it should not be a problem from that side. If someone is spotting the error ...

**Comment by wolfgar** [comment]
Hi Jan,
I just had a very quick overview.
My first remark before diving into the code seriously is : Why do you call m_deinterlacer.Process from ::GetPicture instead of calling it as soon as the frame is decoded and available (case VPU_DEC_OUTPUT_DIS  of ::Decode) ?

**Comment by smallint** [comment]
This is a valid concern. Usually GetPicture is called right after Decode returned VC_PICTURE so I did not see a performance penalty there and our codecinfo buffer is filled which I decided to use as interface to the IPU manager. But you are right, sometimes GetPicture is called more often than Decode which should not make a real difference but the IPU is tasked then more often than required.

What I first tried was to implement for each VPU buffer a corresponding IPU buffer but ran out of memory. So manage a buffer of X IPU buffers that correspond to the render buffers in XBMC. Pulling deinterlacing into Decode means that we need to fill the codecinfo buffer already there. There isn't anything wrong with that its just another state we need to manage  (m_frameInfo and m_currentBuffer) that is used then in GetPicture. I will look into this. Do you think that this could be the cause for black frames? I currently do not see how this can affect the IPU task.

Probably the IPU can only handle input buffers created with IPU_ALLOC. Currently the output buffer is IPU alloc'd and the input buffer is coming from the VPU. If that is the case then the VPU needs to decode into an IPU buffer. Or to put it into other words, all DMA memory can then be allocated with IPU_ALLOC except the extra memory for the VPU. And then I hope that glTexDirectVIV is working with IPU memory as input ;)

**Comment by koying** [comment]
I haven't looked at the code yet, but:
- ::GetPicture is never called more often than ::Decode. Once VC_PICTURE is returned, ::GetPicture is called once for this specific frame. You might have several ::Decode for one ::GetPicture, though.
- I _think_ glTexDirectVIV should work with any type of mem, as we are using the virtual address.
  The performance may vary, though...

**Comment by smallint** [comment]
You are right, I was confused with OutputPicture ;)

**Comment by wolfgar** [comment]
Hi guys,
I don't fear that ::Decode with VC_PICTURE (with is set for VPU_DEC_OUTPUT_DIS) is not called the exact same number of time as ::GetPicture.
It was only a generic question because I first search for the hook at this place thinking that you would have invoked ipu as soon as required data is available. But I don't think ::getpicture is likely to be significantly delayed so it is not really an important question...

**Comment by smallint** [comment]
Has anyone ever played with the VPU-IPU-GPU chain? I just have gstreamer-imx as reference and from what I understand it should work. Since there are no errors logged it is hard to find the problem. I will try to use an IPU buffer for the VPU then. This should be similar to the V4L code of Stephans initial version ...

**Comment by wolfgar** [comment]
Sorry no experience with this chain : Are you sure it has to do with the chain itself?
I mean : Does a unitary test such as the code sample we alluded before work ?
Also, from this sample, the field task.input.deinterlace.enable is only set for odd frames (one out of two) I don't why or if it is a relevant remark but just in case...

**Comment by smallint** [comment]
Yes, the example works. I also modified it to use VPU memory and it is still working. May I should create an EGL test version testing the full chain ...

**Comment by koying** [comment]
I had a look at the code and I think you have a logic problem.
If I understand correctly, the VPU will output 2 pictures that the IPU will merge into 1, right?

If so, your processing should be done in ::Decode, not in ::GetPicture.
More precisely in the

```
 if ((decRet & VPU_DEC_OUTPUT_DIS) ||
          (decRet & VPU_DEC_OUTPUT_MOSAIC_DIS))
```

block.
You should only return VC_PICTURE _after_ IPU has processed 2 interlaced frames to make a progressive one.

**Comment by smallint** [comment]
Not necessarily. The IPU can also deinterlace a single picture. There are two different modes: slow and fast. The code for now switches to either mode depending if a previous frame is available or not. I will build a test app tonight with egl. The code should not produce black frames. A plain fb version works already and you can definitely see deinterlacing of single pictures.

Even in GetPicture we could return a dropped frame if no previous is available.

**Comment by wolfgar** [comment]
According to imx6 RM (§37.4.11), at low level, the VDIC requires at least 3 fields so that its filters can be at play.
But I don't know exactly how the IPU task is plugged and deal with it...

**Comment by smallint** [comment]
OK, a test app with VPU (filled with test data) -> IPU -> GPU works. Now the fun begins ... I logged the time spent in the deinterlacer (ipu queue task) in our codec and it takes around 20ms for 1080i. So it does actually something, just to /dev/null ;)

**Comment by smallint** [comment]
Ahh ... what an awful bug/typo ... reminds me on Chris' problem with "-n" ;)
It is working now. I see deinterlaced frames and it is the first time on IMX6 that horizontal scrollers are perfectly smooth. The deinterlacing itself is not perfect and I think we need to tweak the top/bottom flags correctly but at least a starting point! Cheers

**Comment by wolfgar** [comment]
Congratulations jan !
what was the issue?
For your information, horizontal scrollers were perfectly smooth with my implementation AND the option "mxc_vout.vdi_rate_double=1"
Yet I had a vertical flickering (by one line) which explains why I have not enabled this option  by default
Do you have the same issue ?

**Comment by smallint** [comment]
Thank you Stephan. The issue was that I did not set the virtual address if requested alignment was 0. Just a missing else ;) It took me now two days to figure that out but I have now a small test app for the full chain and it was quite some fun to code it.

Does this kernel option only apply for v4l rendering? I just figured out that I enabled this interpolation stuff on the TV which caused the smooth scrolling. I still need to test Chris branch since my screen is running at 50Hz fixed. So back to normal but deinterlaced. The hockey games were awful to watch without it.

**Comment by smallint** [comment]
I pushed my changes. I added again your config variable IMX_DEINT_MOTION where
- 0 = disabled
- 1 = high motion
- 2 = low motion

Also the streams we were testing with are producing audio lags and dropped frames with deinterlacing enabled: the ones with two fields in one frame that were driving us nuts.

@koying Chris, do you know how to integrate the deinterlacer options into the video options during playback? Then we could nicely switch and test without restarting xbmc.

**Comment by wolfgar** [comment]
Jan,
I think you can do the same as mxc_vout.vdi_rate_double=1 option by setting :
 task.input.deinterlace.field_fmt |= IPU_DEINTERLACE_RATE_EN

Also be aware that deinterlacing is not so cheap not only because of the IPU processing and traffic on the internal bus but also because the maximal resolution out of VDIC is not big enough to hold a 1080p frame (seriously : it is the worst imx6 limitation I am aware of) and the driver splits the frame and handle it as several parts...
So, to begin with tests, maybe you should start with SD streams which will not require this additional splitting and multiple processing...

**Comment by koying** [comment]
@smallint I'm afraid not from the codec. From xbmc pov, deinterlacing is a rendering thing. 
Might be a good idea to move the ipu stuff to the renderer, though (probably once you have stabilized the current code). 
We might use it to do cropping, too. It's currently done in a hacky way :-)

**Comment by smallint** [comment]
I see. I was thinking when starting to move it to the renderer but then we loose time. As I understood the rendering thing (Upload, Render) is called to present a frame so it would be delayed by e.g. some ms due to IPU processing time. The right place would be LinuxRendererGLES::AddProcessor then?

Basically it shouldn't be a big problem but the IPU handle and its associated buffers are held by the codec whereas the actual processing code would be in the renderer. So we either need to move the IPU handle and everything to the renderer as well, share the IPU handle or call a deinterlace method on the codec buffer. It is just a question of architecture and I am currently not too deep into that regarding xbmc.

**Comment by koying** [comment]
Well, we loose time anyway. It is to be assessed whether it hurts. 
The rendering thread is doing little else than rendering, so it might not be noticeable. 

On the subject of performance, we might check later whether enabling tiled output from the vpu would help. If the ipu has to work out frames in chunk, I'd bet it 'd be better, although I'm not sure at that point if we could render it ;-)

**Comment by smallint** [comment]
We could set the input format to tiled NV12, let the IPU deinterlace (and crop) it and output it to a NV12 buffer that is rendered the way it is now. The only thing to be careful about is the special alignment of the input buffer for tiled NV12 required by the IPU. We really would need some unit tests for that to get some numbers. I have a test app but stream reading, demuxing and stuff is all missing ...

**Comment by smallint** [comment]
I pushed another change that disables deinterlacing for "problematic" streams: two fields in one frame and resolution > 1024 (either x or y).

I also tried IPU_DEINTERLACE_RATE_EN which does not show any visual improvements for deinterlaced SD streams and crashes my box for HD. ;)

Has someone already tested it?

**Comment by wolfgar** [comment]
Indirectly only by setting the option mxc_vout.vdi_rate_double which sets this flag...

**Comment by smallint** [comment]
No, I mean the current deinterlacing itself ;)

**Comment by koying** [comment]
Works with the samples I got.
I suggest to merge (after squashing) and fix later if needed.

**Comment by smallint** [comment]
Thanks for the feedback. I create a new PR with squashed commits.

**Comment by koying** [comment]
Just for info, in case you don't know, you can force push to your PR branch and github will pick it up.
No need to create a new branch/PR ;)

**Comment by smallint** [comment]
OK, thanks. I did not know ... still need to learn a lot here.

**Comment by smallint** [comment]
Should we continue the discussion about this feature here or better in a new PR?
Anyhow, I would like to tell about the current findings:
Even when moving the deinterlacing into the renderer it does not help with the Sky streams. For interlaces.ts each deinterlacing takes about 20-30ms but still renders smoothly. The Sky stream deinterlacing takes 15-21ms per frame and produces frame drops. I tried to push deinterlacing into a dedicated thread but this did not help. Then I replaced the deinterlacing (IPU_QUEUE_TASK) call by a simple usleep(25000) to simulate a duration of 25ms and returned the VPU buffer (instead of IPU) and it still renders smoothly. That lets me think that something in the kernel might block something else, e.g. mapping the texture. Normally I would just say that this is a performance limitation of the board but since the interlaced.ts with 30fps instead of 25fps renders well with higher IPU load I just cannot believe that. Any ideas anyone?

**Comment by smallint** [comment]
Quick additional information: when deinterlacing is enabled (Sky stream) the decode times increase and do not fit into the 40ms anymore for many frames -> drops. Without deinterlacing they stay below the 40ms. Hmmm ... can we overclock the VPU? ;)

**Comment by wolfgar** [comment]
@smallint : To overclock VPU you can (and you even should) enable the kernel option CONFIG_MX6_VPU_352M 
Speaking about performance of these platforms, we have to remember that it is not only about CPU power but that bus bandwidth is at play here...

More generally regarding deinterlacing the "only" constraint should be that we have to be able to deinterlace in less time that a (progressive) frame duration  (about 40ms) shouldn't it ?

**Comment by smallint** [comment]
Ahh, interesting. You did not enable that option in your Yocto wandboard config, did you? I will give that a try. And yes, we should be able to deinterlace in less than 40ms (33ms for 30fps) but that is always possible. Decoding time is in this particular more crucial. Before in the sequential setup it was even worse. Thanks for the hint, I am going to test it right now.

**Comment by koying** [comment]
As a matter of fact, the CPU is barely used for pure video playing as it is now ;)

Re the 40ms, there is a bit of overhead, so the interlacing cannot take a full frame duration for itself. From past experience, if an additional processing in the rendering loop took more than 20-25ms, dropped frames appeared, but direct texturing helps, here.

Also, don't forget 30fps means you only get 33ms

**Comment by koying** [comment]
Also, the IPU is the slowing factor, here, not the VPU. So I doubt tweaking the VPU would make deinterlace speedier...

**Comment by smallint** [comment]
Deinterlacing is not the slowing factor in this particular case. As I wrote above, the Interlace.ts sample deinterlaces with up to 32ms and runs smoothly at 30fps while the Sky sample deinterlaces with 21ms and drops frames. I compared the decode times and they are significantly higher with the Sky sample when deinterlacing is in play.

**Comment by koying** [comment]
Ah ok. I understand now.

**Comment by smallint** [comment]
@wolfgar  Wow, that did it! In really data intensive scenes we still have frame drops but overall it looks much better. So I presume the bus bandwidth comes now into play. One possible solution could be to deinterlace directly into a rgb buffer to decrease the GPU work but it would certainly increase memory transfer. So we just need the deinterlace option switcher to disable it from the GUI and probably some drop detector that disables it automatically. Disabling manually would already help. Thanks a lot.

**Comment by smallint** [comment]
Pushed my changes: 497a9db7ea53ee986d07161e5d24e9f2647e05dc
TODO: Use GUI settings

**Comment by wolfgar** [comment]
@smallint : You are right, I have not enabled this option in the kernel configuration in my yocto layer : Since the last update I have realized that it really helps in some cases, that's why I have just mentioned it...

@koying my 40ms margin was not related to the specific implementation that would run this processing in the rendering thread. To me, there might be an architecture that really grants almost the whole frame duration for deinterlacing : After all, we can issue the first deinterlaced picture when it is ready and then we can deinterlace as a parallel process (while decoding and rendering occur : the decoder would decode (n+1) while deinterlacing occurs on (n) and while the rendered frame is (n-1)) : Of course it is easier to say than to implement properly but conceptually it should be doable, don't you think ?

**Comment by koying** [comment]
@smallint Note that I tried setting the output of the IPU to RGBA but I got kernel oops on HD.
I didn't dig further, but I guess reserving (4 (numbuffers) \* 1920 \* 1080 \* 32 (bpp) / 8) dma buffers causes some problems...

@wolfgar You are conceptually right. We could add a 3rd thread for deinterlacing. Synchronizing the 3 threads won't be piece of cake, though ;)
Jan said he already tried and it didn't help, but I don't know how he implemented it.

**Comment by smallint** [comment]
RGBA might be too large for 4 additional IPU buffers, right. And you would need more memory bandwidth to fill it from VPU buffers.

Regarding the thread: I created a third thread running all the time that deinterlaced the current frame in the background and at the next request it returns it. Basically the current Process method was pushing the request into the thread and retrieveing the last result. The pts were not synchronized, deinterlaced frame had the pts of the next. The problem again seems to be that the VPU that takes more time if the IPU is doing its job a the same time. All this would be cool to test with offline apps but I haven't yet been able to produce a simple demuxer app that takes a .ts and starts working. I can push the code, it is still on my box.

**Comment by koying** [comment]
Yeah. I bet the DMA speed/locking is the limiting factor, here. It's awfully slow.
The first implementation of EGL didn't use the direct texture extensions and just copied the VPU output buffers to a "normal" texture. It took 30+ ms just to copy from dma to cpu mem ;)

**Comment by smallint** [comment]
Exactly and since we have now an additional stage (VPU->IPU->GPU->FB) it might be too slow for some streams. I suppose that the old V4L implementation rendered directly into FB from IPU. So one conversion and memory transfer stage less.

**Comment by wolfgar** [comment]
On the other hand, in the previous V4L implementation we always have 2 streams to the IPU for rendering (one for GPU layer and the other for video layer)...

I know I insist on bandwidth but I really think it is a significant piece of this issue.
We might be able to improve the overall behavior by tweaking the AXI priorities (especially by upping VPU prio). I will send to you how to do this fine tuning this evening (I don't have the info at hand right now...)

> Exactly and since we have now an additional stage (VPU->IPU->GPU->FB) it might be too slow for some streams. I suppose that the old V4L implementation rendered directly into FB from IPU. So one conversion and memory transfer stage less.

**Comment by wolfgar** [comment]
me again,
As promised here is data that might be useful to better arbitrate priorities on the NIC-301
Most priorities are described in §45.4.2.3-§45.4.4 of imx6Q RM :
For instance you can change VPU read/write QoS from 2 to 6 by writing 0x6 at addresses 0x00C49100 and 0x00C49104 
The IPU QoS is apart and can be set via IOMUC_GPR6 (§36.3.7) @ address 0x020E0018
(note that its prio is maxed by a kernel patch that enabled to avoid IPU underruns but maybe we can revert this approach and try to find a best compromise)
