### ISSUE TITLE
Deinterlacing causes bad experience with GUI browsing

### ISSUE THREAD

**Issue by wolfgar** [xbmc-imx6/xbmc#40]
When watching SD channels (which are deinterlaced) and browsing the GUI, the video is very jerky and flickering.
If we disable deinterlacing (by setting IMX_DEINT_MOTION environment variable to 0 for instance) then this effect disappears...

**Comment by koying** [comment]
I assume you mean "When watching SD channels (which are **interlaced**)"?
Have you tried with @smallint 's #29 ? Even if it doesn't solve the root issue, it will allow to disable deinterlacing from inside xbmc...

**Comment by wolfgar** [comment]
yes of course , Sorry for the confusion : The streams are interlaced and we deinterlace them.
This deinterlacing process seems to be the root cause for the final flickering/jerky effect.
No I have not tried https://github.com/xbmc-imx6/xbmc/pull/29
I will do it and report quickly... 
(Allowing to enable/disable deinterlacing from xbmc is handy and user friendly but is not a fix of course)

**Comment by koying** [comment]
An explication might be a race between the IPU and EGL. If so, moving the deinterlacing to the render loop might actually solve it...

**Comment by wolfgar** [comment]
Yes you are right this PR may be really useful
So I have just given it a try : The original effect described here is mainly solved.

But I am not convinced by the deinterlacing itself : 
I have dropped the env variable IMX_DEINT_MOTION, 
In video OSD, I set "Deinterlace video" to "auto" and "Deinterlace method" to "De-interlace" 
And the deinterlacing is bad : something seems to happen compared to no deinterlacing but still very visible artifacts : I will revert and compare to be sure but it seems to me that deinterlacing correction is visibly worse with this PR than without...

**Comment by smallint** [comment]
Please try to set "Deinterlace method" to "auto" which will use fast motion instead of low motion (De-interlace) though both is working for me with SD channels. HD allows only fast motion probably due to performance reasons.

**Comment by wolfgar** [comment]
Thanks for the tips ! 
switching  "Deinterlace method" to "auto" makes the PR29 behaves significantly better
My eyes were not so wrong ;)
So I guess it is all good :  this issue can be closed as soon as we merge #29 ...

**Comment by wolfgar** [comment]
with #29 merged, this issue is solved
