### ISSUE TITLE
VC1 videos are jerky

### ISSUE THREAD

**Issue by wolfgar** [xbmc-imx6/xbmc#41]
Following a [report](http://forum.xbmc.org/showthread.php?tid=161793&pid=1651545#pid1651545) on xbmc forums, I have just given a try at a VC1 stream and it is jerky.
I am currently investigating the issue so I am assigning this issue to myself ...

**Comment by smallint** [comment]
I don't want to stress this synchronization topic too much but when watching HD streams I have from time to time very small de-sychronized frames, maybe one/two frames every 2-3 seconds. This effect persits for about 1 minutes and recovers itself. Might be related to VPU, overall stress, don't know ... the IPU is not involved at all.

**Comment by wolfgar** [comment]
HD streams using which codec ?
I really have no issue at all with h264 (avc codec) in mkv containers on my side even for high bitrates

**Comment by koying** [comment]
Tested with http://download.openbricks.org/sample/VC1/ and I don't see the issue.
Would you mind sharing the sample you're using?

**Comment by wolfgar** [comment]
Try this [one](http://www.techpowerup.com/downloads/530/hd-dvd-demo-1080p-vc-1-ddplus-5-1/) for instance
Maybe it is too demanding (18mbps) and hdaudio to decode (but even with passthrough the issue remains)  ?

**Comment by koying** [comment]
Yep, confirmed with this one. 
Note that it is 29.97fps, which doesn't help ;)

**Comment by wolfgar** [comment]
with #47 and #42 merged, now vc1 plays fine ...
