### ISSUE TITLE
MKV file ... Audio is there but no video output (sample included)

### ISSUE THREAD

**Issue by cjcr** [xbmc-imx6/xbmc#44]
<b>Edit:</b> Related to https://github.com/xbmc-imx6/xbmc/pull/43

Hi,

I have several MKV files, in this a case a full season of TBBT. The first episode works, but the other (all others of this season) doesn't work.

No video output (but audio works well).

Platform: TBS Matrix. imx6q (latest version of this xbmc branch)

Here the video details:

General
Unique ID                      : 190744794500011437496090088147034520897 (0x8F801C74166CD85695BF7E3026573D41)
Complete name                  : The Big Bang Theory 6x03 Spa 720p.mkv
Format                         : Matroska
Format version                 : Version 2
File size                      : 201 MiB
Duration                       : 19mn 34s
Overall bit rate               : 1 434 Kbps
Encoded date                   : UTC 2012-11-03 02:29:17
Writing application            : mkvmerge v5.8.0 ('No Sleep / Pillow') built on Sep  2 2012 15:37:04
Writing library                : libebml v1.2.3 + libmatroska v1.3.0

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High 10@L5.1
Format settings, CABAC         : Yes
Format settings, ReFrames      : 4 frames
Codec ID                       : V_MPEG4/ISO/AVC
Duration                       : 19mn 34s
Nominal bit rate               : 1 300 Kbps
Width                          : 1 280 pixels
Height                         : 720 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 23.976 fps
Original frame rate            : 25.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.059
Writing library                : x264 core 125 r2208 d9d2288
Encoding settings              : cabac=1 / ref=3 / deblock=1:-1:-1 / analyse=0x1:0x111 / me=hex / subme=5 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=2 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=1300 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Default                        : Yes
Forced                         : No

Audio
ID                             : 2
Format                         : AAC
Format/Info                    : Advanced Audio Codec
Format profile                 : LC
Codec ID                       : A_AAC
Duration                       : 19mn 34s
Channel(s)                     : 2 channels
Channel positions              : Front: L R
Sampling rate                  : 48.0 KHz
Compression mode               : Lossy
Language                       : Spanish
Default                        : Yes
Forced                         : No

<b>Download link:</b> https://www.dropbox.com/s/6hnx4nlfdilfvdr/The%20Big%20Bang%20Theory%206x03%20Spa%20720p.mkv

**Comment by koying** [comment]
This is related to #43 I think. Hi10 is not supported by the vpu, so we have to fallback to (choppy) software.

**Comment by cjcr** [comment]
@koying Could be because the first episode works and it says:
Format profile: Main@L3.1

And this one is:
Format profile: High 10@L5.1

Sad :(

**Comment by koying** [comment]
As I pointed out in the xbmc forum thread, unfortunately for anime lovers, there is no SoC that I know that does hi10, yet...

**Comment by cjcr** [comment]
Well, I updated the first post and I added the link to the file with problems if it helps but if isn't supported by hardware we can't expect good results ...

Thanks and sorry for the noise. :D

**Comment by wolfgar** [comment]
Yes, we cannot do more than #43 unfortunately.
So I close this bug report...
