### ISSUE TITLE
I am getting "iccp known incorrect srgb profile" and the blue turn red

### ISSUE THREAD

**Issue by dbmello75** [xbmc-imx6/xbmc#48]
Hi, My XBMC Confluence is red instead blue. When I try to restart the XBMC gui i getting the message:
libpng warning: iCCP: known incorrect sRGB profile.
This is a fresh install .

**Comment by wolfgar** [comment]
I have never seen this behavior...
I doubt it is related to an issue with the code hosted in this repo : Which board and which build do you use?

**Comment by dbmello75** [comment]
Sorry for that. I am using a Wandboard Quad with wandq__yocto_v0.0.4.img and a 2TB HDD on it. 
I use XBMC more then 6 years and it's the first time I see it too. 
First I thought it is because I map my 2TB HDD in /home/root/ (its make XBMC faster). Then I make a fresh install and the problem comeback again. 
Sometimes its start ok, sometimes its start RED (Confluence should be blue) and sometimes its start normal (blue) then it turn red.
The red screen comes when start xbmc on command line and get this :

root@wandboard-quad:~# /imx6/xbmc/lib/xbmc/xbmc.bin
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: cHRM chunk does not match sRGB
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
![img_20140323_153656](https://f.cloud.github.com/assets/6946779/2494215/82c52d40-b2bc-11e3-97ec-63f023a9a61b.jpg)

**Comment by smallint** [comment]
I have the same warning on the command line since the very first time I started xbmc on my Wandboard but I do not care too much. I have never seen the red screen though it looks pretty cool, doesn't it ;)

**Comment by wolfgar** [comment]
Hmm ok, it is my yocto image : I have never been able to get this nice red screen in spite of the libpng warnings ;)
More seriously, have you checked another image (not xbmc related) ? have you checked your cables and your monitor ? I also have a wandboard (among other boards) and I have a correct skin display...
If you want to give a try at a newer image based on this new repo, you can test that [one](https://stephan-rafin.net/owncloud/public.php?service=files&t=488a802fbe553080b9c80e91e0abd292)

**Comment by dbmello75** [comment]
I like the red screen too, very much. But films and the pictures get the wrong colors :(. I will try another image, including Android and Ubuntu. I will report the results soon. 
PS: I am from Brazil, so ignore my bad english, please.

**Comment by dbmello75** [comment]
Hi, I tried this ways:
Android = Colors are ok
Ubuntu = Colors are ok
wandq_yocto_v0.0.5 = I get red screen Again. I tried my second wandboard, Red again. But I changed the TV to Cable TV receiver and when I get back the colors are OK. I am lost. 
There are any debug to make???

**Comment by dbmello75** [comment]
So, I think I discovered the problem. 
My HTPC: Wandboard + 8GB Sd + 2TB HDD + Yocto + XBMC (let's call it XBMC)
My Home Cinema: XBMC + HT Yamaha RX-V663 + TV Panasonic Plasma.
The XBMC is on HT Yamaha, what is conected on my TV Panasonic in HDMI2 input. Each time i change the video source, it's turn red and blue. For now, when I get red, I change the source again and get the right color.

**Comment by wolfgar** [comment]
OK, so it is related to your audio receiver, right ?
If you directly connect the wandboard to the TV, can you see the problem ?

**Comment by wolfgar** [comment]
I am closing this now as it seems to be related to the installation and no input for one week...
