### ISSUE TITLE
Query and change resolution 

### ISSUE THREAD

**Issue by smallint** [xbmc-imx6/xbmc#5]
According to the post of @koying in the dev forum:

On the resolution subject, I can query the available resolutions with

```
cat /sys/class/graphics/fb0/modes
```

and dynamically change it with, e.g.

```
echo 1 > /sys/class/graphics/fb0/blank
echo U:1280x720p-60 > /sys/class/graphics/fb0/mode
echo 0 > /sys/class/graphics/fb0/blank
```

so I'll implement that in CEGLNativeTypeIMX.
Only problem is that /sys/class/graphics/fb0/mode is root:root 644

**Comment by koying** [comment]
Yeah. That's probably not the good way, as I don't see how to circumvent the root:root part and running xbmc as root is out-of-question.

To be investigated further how we could use FBIOPUT_VSCREENINFO  for this

**Comment by koying** [comment]
Looks like using fb ioctl will really be too complicated.
I'll implement the "/sys/class/graphics/fb0/mode" way, leaving to the sysadmin to give proper permissions, e.g. in an init.d script.

**Comment by smallint** [comment]
Sounds good as a first starting point. I am running xbmc as root so no big issue there. When proper X or Wayland support is ready your implementation is obsolete anyway.

I was struggling with exactly the same issue some time ago and after studying the fbset code I came to the conclusion that is is not easy if not impossible to do that without root privileges. Usually we X or other display server for that. Alternatively you need a proper fbmode database. You can also let the creation to the distributor or the user and just rely on this one in an ioctl implementation.

**Comment by CrawX** [comment]
I have had good experience using the (still not very clean) fbsysfs-method.
I used [a plugin](https://github.com/pilluli/service.xbmc.callbacks) that allowed me to execute a script onPlaybackStart/Stopped and used a script like this 

``` bash

#!/bin/bash
sleep 1
curl --silent -o /dev/null -i -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "Player.PlayPause", "params": { "playerid": 1 }, "id": 1 }' http://xbmc:xbmc@127.0.0.1:8080/jsonrpc
fps=`grep "fps:" /home/xbmc/.xbmc/temp/xbmc.log | tail -n 1 | awk '{print $5}' | cut -c 1-2`
sleep 1
case "$fps" in
        "24" | "23" )
                fps="24"
                ;;
        "25" )
                fps="25"
                ;;
        "30" )
                fps="30"
                ;;
        *)
                fps="60"
esac
echo "Switching to $fps"
echo "S:1920x1080p-$fps" > /sys/class/graphics/fb0/mode
sleep 4
curl --silent -o /dev/null -i -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "Player.PlayPause", "params": { "playerid": 1 }, "id": 1 }' http://xbmc:xbmc@127.0.0.1:8080/jsonrpc
```

 to pause playback, change the refresh rate and then resume again. The only problems I had using this was the audio would get async most of the time, simply skipping +30s and then -30s would fix this issue.

However, this was all done using the imx-wip branch by wolfgar and it does NOT work correctly using master of this repo. Changing the refresh rate at playback start basically screws up the whole playback: the only thing I can see after the resolution changes is the normal tty login (audio still plays). I'd have to fool around with it a bit more to narrow down the source of the issue..

During my tests, FB_MULTI_BUFFER was set to 2.

Best regards,
CruX

Edit: I'm using the 3.10.17 vivante binaries with wolfgars kernel (patched to allow the usage of said binaries).

**Comment by koying** [comment]
Yep, that 's the way I plan to implement it, but from inside XBMC, so that should avoid the problems you are experiencing.

**Comment by CrawX** [comment]
Implementing the refresh-rate change before the actual playback is started could actually fix those problems, lets see how your implementation works. I'd be happy to test!

Cheers!

**Comment by koying** [comment]
Spent a day understanding "/sys/class/graphics/fb0/mode" REQUIRES a linefeed :(
Doing `echo -n "S:1920x1080p-$fps" > /sys/class/graphics/fb0/mode` fails...

**Comment by koying** [comment]
PR: https://github.com/xbmc-imx6/xbmc/pull/10

**Comment by wolfgar** [comment]
Can we close this feature now ?

**Comment by smallint** [comment]
Yes. All further bad downstream behaviour is then a bug and can be opened as such ;)
