### ISSUE TITLE
CheckCompatibility on 3.10.17 (wandboard)

### ISSUE THREAD

**Issue by CrawX** [xbmc-imx6/xbmc#51]
Hey everyone,

I was finally able to get xbmc up and running on 3.10.17 on my Wandboard Quad.
I am using the [official beta kernel](https://github.com/wandboard-org/linux/tree/wandboard_imx_3.10.17_1.0.0_beta) on archlinux (using the config provided [here](https://github.com/archlinuxarm/PKGBUILDs/tree/master/core/linux-imx6-wandboard-dt)).

However, builds built off master do not run on this kernel, because `CEGLNativeTypeIMX::CheckCompatibility()` returns false.

`/sys/class/graphics/fb0/device/modalias` doesn't contain the needed magic string but just contains `platform:fb.24`.
Because I didn't know how to detect a mxcfb otherwise, I fixed this by alyways returning true (which of course does not make sense for normal builds).

Anyhow, xbmc does seem to run fine now! I tested 1080p playback via hdmi.

Cheers!

**Comment by wolfgar** [comment]
Thanks a lot for this feedback, it is really good to see that wandboard 3.10 kernel is also available and able to run xbmc now.
I guess we have to find a better way to probe that we are indeed on imx6 with egl available...

**Comment by dbmello75** [comment]
I don't know howto compile it, but if you send an 0.0.6 update I can test
it.

Diorgenes Mello

---

+55 (27)9972-1430
+55 (27)3295-4031

**Comment by CrawX** [comment]
I'm no expert on this, but wouldn't checking for existence of `/sys/class/graphics/fb0/fsl_disp_dev_property` work? To me, the fsl_ prefix strongly suggests that this might be freescale-only...

Glad to have it running on 3.10!

Cheers

**Comment by tomlohave** [comment]
Le 29/03/2014 20:17, CrawX a écrit :

> I'm no export on this, but wouldn't checking for existence of 
> |/sys/class/graphics/fb0/fsl_disp_dev_property| work? To me, the fsl_ 
> prefix strongly suggests that this might be freescale-only...
> 
> at least this file exists on cuboxi
> 
> Glad to have it running on 3.10!
> 
> Cheers

B.R

> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xbmc-imx6/xbmc/issues/51#issuecomment-39005779.

## 

www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by wolfgar** [comment]
And it exists in 3.0.35 too so it sounds like an interesting suggestion...
I will submit a patch according to this idea, thanks...

**Comment by tomlohave** [comment]
can you check if it works with https://github.com/xbmc-imx6/xbmc/pull/57 ?

**Comment by CrawX** [comment]
Just build the master branch plus your pr and can confirm that it works nicely :)
Again, this is 3.10.17 on the wandboard quad.
Thanks.

**Comment by Toverkwark** [comment]
Hey CrawX. How did you make it work? I tried this:
-Freshly install archlinuxarm by following the install on their website
-Built and installed https://github.com/archlinuxarm/PKGBUILDs/tree/master/core/linux-imx6-wandboard-dt as a package
-Then built and installed https://github.com/archlinuxarm/PKGBUILDs/tree/master/alarm/xbmc-imx

Although it seemed to work somehow, the screen is black and white, seems to have some sort of interlacing problem and is I guess not phased correctly since it starts at about 1/3rd and seems to fold over at the other end. 

Any idea what I'm doing wrong? Could you shortly give an outline of how you made it work on archlinux on 3.10.17?

**Comment by pepedog** [comment]
Toverkwark, I don't know why you built the as they are in Archlinuxarm repo
You need to add consoleblank=0 to bootargs probably via uEnv.txt

**Comment by Toverkwark** [comment]
Thanks and forgive my ignorance, I'm rather new to this stuff. How should I have done it instead if not building from the archlinux repo? I'll try your suggestion tonight to see if it works.

**Comment by Toverkwark** [comment]
ah right, I misunderstood your answer, I guess you meant there was no need to build them. I also tried the pre-built repo's and they gave me the same behavior, that's why I decided to build myself to see if it would make a difference.

**Comment by pepedog** [comment]
As simple as
http://archlinuxarm.org/forum/viewtopic.php?f=45&t=6815&start=70#p39196 (ignore boot.scr part)
And if creating a text file is hard, 
http://archlinuxarm.org/forum/viewtopic.php?f=45&t=7107#p39135

**Comment by CrawX** [comment]
hey @Toverkwark,

I'm not really sure about that, but I guess that it comes down to [this](http://archlinuxarm.org/forum/viewtopic.php?f=45&t=7068) problem.
The solution in this case was to add `video=mxcfb0:dev=hdmi,1920x1080M@60,if=RGB24,bpp=16` to /boot/uEnv.txt. Although I'm not sure about this freescale magic, I'd give it a try.

Other than that, I'm running the buildbot-built version available via the pacman repository.

Cheers

**Comment by Toverkwark** [comment]
Thanks! Adding that line to /boot/uEnv.txt solved the problem, although it seemed to create another small one. Now, every time I have to reboot, the board seems very often to get stuck early in boot. I have to press the reset button 5-6 times before it goes through again. Unfortunately I don't have a console to see what's happening there.

**Comment by CrawX** [comment]
I probably have a related problem where by board boots fine when I press reset but just doesn't when I `systemctl reboot`. Its stuck at `Starting kernel`.

Still, glad it worked for you :)

**Comment by wolfgar** [comment]
I close this issue : xbmc runs fine on 3.10 and the compatibility check has been implemented by tomlohave and merged for a while now...
