### ISSUE TITLE
New Release for GeeXboX Utilite

### ISSUE THREAD

**Issue by SharpNoiZy** [xbmc-imx6/xbmc#73]
Hi,

is there already a plan for a new release with XBMC 13.1 for the Utilite version of GeeXboX, because the official software support for Utilite is really bad!
At the moment I spend 200€ for great hardware which lays in the corner because of bad software! ;(

Kind regards

**Comment by warped-rudi** [comment]
http://download.geexbox.org/snapshots/geexbox-xbmc-imx6-utilite/

Please ask GeexBox related questions either in the forum

http://www.geexbox.org/forum/

or here 

https://github.com/OpenBricks/openbricks/
