### ISSUE TITLE
CAESinkALSA has problems parsing the imx6 ELD

### ISSUE THREAD

**Issue by susisstrolch** [xbmc-imx6/xbmc#78]
Seems either the kernel or the ALSA connector has  a problem to detect the ELD from imx6 (Cubox-i4pro with AVR attached).
Here's the ELD information:
[    1.722030] mxc_hdmi 20e0000.hdmi_video: mxc_edid_read_internal
[    1.996217] cea extent revision 3
[    1.996222] CEA underscan 1
[    1.996224] CEA basicaudio 1
[    1.996225] CEA ycbcr444 1
[    1.996227] CEA ycbcr422 1
[    1.996229] CEA Short desc timmings
[    1.996231] Tagcode 2 Len 18
[    1.996234] Support CEA Format #16
[    1.996236] Support CEA Format #31
[    1.996238] Support CEA Format #4
[    1.996240] Support CEA Format #19
[    1.996242] Support CEA Format #5
[    1.996244] Support CEA Format #20
[    1.996246] Support CEA Format #3
[    1.996248] Support CEA Format #18
[    1.996250] Support CEA Format #32
[    1.996252] Support CEA Format #33
[    1.996254] Support CEA Format #34
[    1.996256] Support CEA Format #7
[    1.996258] Support CEA Format #15
[    1.996260] Support CEA Format #30
[    1.996262] Support CEA Format #1
[    1.996265] Tagcode 1 Len 21
[    1.996267] Audio Format Descriptor :  1
[    1.996269] Max Number of Channels  :  8
[    1.996271] Sample Rates            : 7f
[    1.996273] Sample Sizes            : 07
[    1.996275] Audio Format Descriptor :  7
[    1.996277] Max Number of Channels  :  6
[    1.996279] Sample Rates            : 1e
[    1.996281] Audio Format Descriptor :  2
[    1.996283] Max Number of Channels  :  6
[    1.996285] Sample Rates            : 07
[    1.996287] Audio Format Descriptor : 11
[    1.996289] Max Number of Channels  :  8
[    1.996290] Sample Rates            : 7e
[    1.996292] Audio Format Descriptor : 10
[    1.996294] Max Number of Channels  :  8
[    1.996297] Sample Rates            : 06
[    1.996299] Audio Format Descriptor : 12
[    1.996301] Max Number of Channels  :  8
[    1.996303] Sample Rates            : 7e
[    1.996304] Audio Format Descriptor :  9
[    1.996306] Max Number of Channels  :  6
[    1.996308] Sample Rates            : 02
[    1.996310] Tagcode 4 Len 3
[    1.996312] Speaker Alloc           : 5f
[    1.996315] Tagcode 3 Len 18
[    1.996317] VSD hdmi capability 1
[    1.996319] VSD support ai 1
[    1.996321] VSD support deep color 48bit 0
[    1.996322] VSD support deep color 36bit 1
[    1.996324] VSD support deep color 30bit 1
[    1.996326] VSD support deep color y444 1
[    1.996328] VSD support dvi dual 0
[    1.996330] VSD MAX TMDS CLOCK RATE 225
[    1.996331] VSD cnc0 1
[    1.996333] VSD cnc1 0
[    1.996335] VSD cnc2 0
[    1.996336] VSD cnc3 0
[    1.996338] latency_present 0
[    1.996340] I_latency_present 0
[    1.996341] hdmi_video_present 1
[    1.996343] hdmi_3d_present 1
[    1.996345] hdmi_3d_multi_present 2
[    1.996347] hdmi_vic_len 0
[    1.996348] hdmi_3d_len 8
[    1.996351] HDMI 3d struct all =0x140
[    1.996353] HDMI 3d mask all =0x73f
[    1.996354] Support 3D video format
[    1.996357] vic_order_2d=4, 3d_struct=0, 3d_detail=0x0
[    1.996361] vic_order_2d=5, 3d_struct=0, 3d_detail=0x0
[    1.996364] vic_order_2d=9, 3d_struct=0, 3d_detail=0x0
[    1.996367] vic_order_2d=10, 3d_struct=0, 3d_detail=0x0
[    1.996369] Tagcode 7 Len 3
[    1.996371] Not handle block, tagcode = 0x7
[    1.996373] Tagcode 7 Len 2
[    1.996375] Not handle block, tagcode = 0x7
[    1.996376] CEA long desc timmings
[    1.996379] Aspect ratio: 16:9
[    1.996390]       74 MHz 1920 2448 2492 2640 540 542 547 562 +HSync +VSync
[    1.996390] 
[    1.996392] Aspect ratio: 16:9
[    1.996401]       74 MHz 1920 2008 2052 2200 540 542 547 562 +HSync +VSync
[    1.996401] 

And here what XBMC is thinking about...
13:12:14 T:1984155648   DEBUG: CAESinkALSA: snd_hctl_find_element=0
13:12:14 T:1984155648   DEBUG: CAESinkALSA - Unable to obtain ELD information for device "hdmi:CARD=imxhdmisoc,DEV=0" (not supported by device, or kernel older than 3.2)
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_LPCM" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_DTSHD" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_TRUEHD" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_EAC3" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_DTS" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_AC3" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: CAESinkALSA::EnumerateDevice data format "AE_FMT_AAC" on device "hdmi:CARD=imxhdmisoc,DEV=0" seems to be not supported.
13:12:14 T:1984155648  NOTICE: Found 1 Lists of Devices
13:12:14 T:1984155648  NOTICE: Enumerated ALSA devices:
13:12:14 T:1984155648  NOTICE:     Device 1
13:12:14 T:1984155648  NOTICE:         m_deviceName      : sysdefault:CARD=imxhdmisoc
13:12:14 T:1984155648  NOTICE:         m_displayName     : imx-hdmi-soc
13:12:14 T:1984155648  NOTICE:         m_displayNameExtra: HDMI #
13:12:14 T:1984155648  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
13:12:14 T:1984155648  NOTICE:         m_channels        : FL,FR,BL,BR,FC,LFE,SL,SR
13:12:14 T:1984155648  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
13:12:14 T:1984155648  NOTICE:         m_dataFormats     : AE_FMT_LPCM,AE_FMT_DTSHD,AE_FMT_TRUEHD,AE_FMT_EAC3,AE_FMT_DTS,AE_FMT_AC3,AE_FMT_AAC,AE_FMT_S16NE,AE_FMT_S16LE
13:12:14 T:1984155648  NOTICE:     Device 2
13:12:14 T:1984155648  NOTICE:         m_deviceName      : hdmi:CARD=imxhdmisoc,DEV=0
13:12:14 T:1984155648  NOTICE:         m_displayName     : imx-hdmi-soc
13:12:14 T:1984155648  NOTICE:         m_displayNameExtra: HDMI #0
13:12:14 T:1984155648  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
13:12:14 T:1984155648  NOTICE:         m_channels        : FL,FR,BL,BR,FC,LFE,SL,SR
13:12:14 T:1984155648  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
13:12:14 T:1984155648  NOTICE:         m_dataFormats     : AE_FMT_LPCM,AE_FMT_DTSHD,AE_FMT_TRUEHD,AE_FMT_EAC3,AE_FMT_DTS,AE_FMT_AC3,AE_FMT_AAC,AE_FMT_S16NE,AE_FMT_S16LE
13:12:14 T:1984155648  NOTICE:     Device 3
13:12:14 T:1984155648  NOTICE:         m_deviceName      : sysdefault:CARD=imxspdif
13:12:14 T:1984155648  NOTICE:         m_displayName     : imx-spdif
13:12:14 T:1984155648  NOTICE:         m_displayNameExtra: S/PDIF #
13:12:14 T:1984155648  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
13:12:14 T:1984155648  NOTICE:         m_channels        : FL,FR
13:12:14 T:1984155648  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
13:12:14 T:1984155648  NOTICE:         m_dataFormats     : AE_FMT_AC3,AE_FMT_DTS,AE_FMT_S24NE4,AE_FMT_S16NE,AE_FMT_S16LE
13:12:14 T:1984155648  NOTICE:     Device 4
13:12:14 T:1984155648  NOTICE:         m_deviceName      : iec958:CARD=imxspdif,DEV=0
13:12:14 T:1984155648  NOTICE:         m_displayName     : imx-spdif
13:12:14 T:1984155648  NOTICE:         m_displayNameExtra: S/PDIF #0
13:12:14 T:1984155648  NOTICE:         m_deviceType      : AE_DEVTYPE_IEC958
13:12:14 T:1984155648  NOTICE:         m_channels        : FL,FR
13:12:14 T:1984155648  NOTICE:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
13:12:14 T:1984155648  NOTICE:         m_dataFormats     : AE_FMT_AC3,AE_FMT_DTS,AE_FMT_S24NE4,AE_FMT_S16NE,AE_FMT_S16LE
13:12:14 T:1984155648   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/appliance.xml

Especially the AVR 24bit capability for LPCM doesn't show up in the parsed device info.

**Comment by warped-rudi** [comment]
The imx audio driver does not support the ELD control. Therefore XBMC cannot retrieve this info. But it's not really necessary anyway. 24bit PCM support is detected by other means.

**Comment by warped-rudi** [comment]
24bit as well as multichannel PCM support has been fixed in the kernel. There is still room for improvement (ALSA channel mapping API), but this is not an XBMC issue. Therefore I close this.
