### ISSUE TITLE
HDMI connection lost after a few minutes of playback or idleing

### ISSUE THREAD

**Issue by andrenam** [xbmc-imx6/xbmc#85]
Hi,

Hardware: 
- wandboard quad
- Denon AVR-1610 AV-Receiver
- Samsung LCD-TV

Software: 
Archlinuxarm, Kernel linux-wandboard 3.10.17-4
xbmc, xbmc-imx-git 13.20140806-1
firmware-imx 3.10.17_1.0.0.-1
imx-vpu 3.10.17_1.0.0-2

Problem:
The wandboard is connected via HDMI to the Denon AV-Receiver, audio is set to passthrough.
After a few minutes of video playback (mkv, x264, DTS, _not DTS-HD_), the HDMI connection between the wandboard and the AV receiver is lost. I get no more audio and no image. But XBMC itself is still responsive via the webinterface or android remote app in the background. 

In the xbmc.log, I get  a lot of those errors:

```
ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
..
ERROR: AddPackets - failed to add leftover bytes to render
..
```

and eventually followed by  

```
..
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CActiveAESink::OutputSamples - failed
ERROR: CAESinkALSA::Initialize - failed to initialize device "sysdefault:CARD=imxhdmisoc"
```

CPU Load during playback seems okay. 

**Complete debugging log: http://pastebin.com/tWxrZ1Lt**

Any idea, guys? :-)

**Comment by andrenam** [comment]
UPDATE: Surprisingly, I have the same symptons when I idle in the menu for a few menus without pressing any buttons.

```
ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)
DEBUG: Thread JobWorker 1694495776 terminating (autodelete)
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CAESinkALSA::HandleError(snd_pcm_writei(2)) - snd_pcm_writei returned -5 (Input/output error)
ERROR: CActiveAESink::OutputSamples - failed
ERROR: CEngineStats::UpdateSinkDelay - inconsistency in buffer time
```

**Complete log with debugging: info http://pastebin.com/nQLs5pFe**

Additional info: _I am running MPD (music player daemon) using the SPDIF sound output via ALSA on the same machine/wandboard._
But at the time, mpd playback was paused, so I think the audio device **should** not be blocked. 
But I'll try without mpd running ...

Sooo, shutting mpd down before starting xbmc doesn't help. Apparently, running the mpd daemon in the background was not the problem. I did get a lot of these errors:

```
DEBUG: CDVDPlayerAudio:: Discontinuity1 - was:553461695.556087, should be:552287666.666667, error:-1174028.889421
ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
```

**Comment by warped-rudi** [comment]
And you have disabled automatic screen blanking (i.e. consoleblank=0 on the kernel command line)?

**Comment by andrenam** [comment]
Oh no, I did not. Added that to my /boot/uEnv.txt file. Thank you, Rudi :)
Haven't testet it in full detail, but so far it seems good (had only 10-15 minutes time to test).
