### ISSUE TITLE
Segmentation fault after 10 minutes playback

### ISSUE THREAD

**Issue by jaarandaz** [xbmc-imx6/xbmc#95]
Hi!

Doesn't matters if it is audio or video, after 10 minutes xbmc has a segmentation fault. I'm using latest Archlinux image on a Wandboard Quad, kernel version 3.10.17-5-ARCH and XBMC version 13.2 Git:20140909-38110c5.

XBMC's log shos this kind of error:
`ERROR: CAESinkALSA - snd_pcm_writei(-5) Input/output error - trying to recover`
`ERROR: CAESinkALSA::HandleError(snd_pcm_writei(1)) - snd_pcm_writei returned -5 (Input/output error)`

Archlinux's journal says:
`kernel: imx-hdmi-audio imx-hdmi-audio: HDMI Video is not ready!`
`kernel: imx-hdmi-audio imx-hdmi-audio: ASoC: can't open platform imx-hdmi-audio: -22`
`runxbmc[254]: [     1] Process got signal (8). To further debug the issue, you should run in debug mode`
`runxbmc[254]: /usr/bin/runxbmc: line 11:   264 Floating point exception(core dumped) /usr/lib/xbmc/xbmc.bin $@`

It seems xbmc is killed by a SIGFPE. There is any way of solve this? Thanks!

**Comment by wolfgar** [comment]
hmm I have never seen this issue (and I can tell you I run kodi for hours, both to watch tv and to test for dev purposes)

To investigate this specific crash, I would need a core dump.
Could you 
- Stop XBMC
- login on the board and issue the commands :

echo "/tmp/core.%e.%p" > /proc/sys/kernel/core_pattern
ulimit -c unlimited

then launch xbmc binary from the same shell 
That way on next crash you will have a core dump saved in /tmp folder

**Comment by jaarandaz** [comment]
One more thing: after crashing (and relaunch), hdmi audio output option is not shown.

asRoot# /usr/bin/xbmc-standalone :0
`[INFO] Product Info: i.MX6Q/D/S`
`[INFO] bitstreamMode 1, chromaInterleave 1, mapType 0, tiled2LinearEnable 0`
`[     1] Process got signal (8). To further debug the issue, you should run in debug mode`
`/usr/bin/xbmc: line 144:   289 Floating point exception(core dumped) "$LIBDIR/xbmc/xbmc.bin" $SAVED_ARGS`
`Crash report available at /root/xbmc_crashlog-20140921_223218.log`

Compressed core dump:
https://arandaz.com/owncloud/public.php?service=files&t=f094fc8a21a6e5250191d145302fd92f

**Comment by jaarandaz** [comment]
Is there anything I can do?

**Comment by wolfgar** [comment]
Hi

Very sorry : I hadn't the required binaries version from archlinux to properly debug postmortem
the sound thread is indeed badly crashing 
Have you had the opportunity to test another release ?
That is strange because my own (almost daily builds) do not exhibit the issue...

**Comment by CrawX** [comment]
@jaarandaz Also tried to reach me via the archlinux-arm forums.

Unfortunately, I have not seen this specific issue. My xbmc crashes from time to time (mostly after long idle times). I have not seen your situation though.

Are you running the build from the repo or have you compiled it yourself?

**Comment by jaarandaz** [comment]
Hi @CrawX 

sorry for being annoying. I'm installing xbmc-imx using https://github.com/archlinuxarm/PKGBUILDs 
Maybe the problem is in the kernel (even though I'm using the one that comes with archlinux's wandboard image)

**Comment by jaarandaz** [comment]
Hi!

I finally found the problem. Or the fix. The thing is that you HAVE to use "consoleblank=0" on uEnv.txt or this will happen. Thanks to all :smile:

**Comment by wolfgar** [comment]
Ho damn. It explains why I have never ever been able to reproduce this bug !
Thanks a lot for this additional feedback : I have to admit I wad unable to reproduce as it and I did not understand why the hell you were the only person to experience this issue...

**Comment by pepedog** [comment]
I should have figured this out, 10 minutes is a dead giveaway. It completely slipped my mind on this occasion.
It's in uEnv.txt default for CuBox-I/hummingboard
